apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/dist-sys-week2/frontend:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: gcr-json-key-frontend
